FROM maven:3.8.4-openjdk-21-slim AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/target/reserva*.jar /app/reserva.jar
EXPOSE 8082
ENTRYPOINT [ "java", "-jar", "reserva.jar" ]